dependencies = [
  "Array.prototype.forEach",
  "Element",
  "Function.prototype.bind",
  "Map",
  "MutationObserver",
  "Node.prototype.contains",
  "Object.defineProperty",
  "Set",
  "WeakMap"
]
license = "W3C"
spec = "https://html.spec.whatwg.org/multipage/interaction.html#inert"
repo = "https://github.com/WICG/inert"
docs = "https://github.com/WICG/inert/blob/master/explainer.md"

[browsers]
edge = "*"
edge_mob = "*"
ie = "8 - *"
ie_mob = "8 - *"
firefox = "*"
opera = "*"
safari = "*"
chrome = "<76"
ios_saf = "*"
firefox_mob = "*"
android = "*"

[install]
module = "wicg-inert"
paths = [ "dist/inert.js" ]

